import express from 'express';
import mongoose from 'mongoose';
const app = express();
app.use(express.json());
console.log('SHIVA MOTORS SERVER BOOTING...');
const mongoURI = process.env.MONGO_URI || '';
mongoose.connect(mongoURI).then(() => console.log('MongoDB successfully connected!')).catch((err) => console.error('CRASH [MongoDB Connection Error]:', err));
app.get('/', (req, res) => { res.send('Shiva Motors Backend is Live!'); });
const PORT = process.env.PORT || 3000;
app.listen(Number(PORT), '0.0.0.0', () => { console.log('Server running on port ' + PORT); });
